blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://idom-docs.herokuapp.com/
    about: Learn more about how IDOM works
  - name: Community Support
    url: https://github.com/idom-team/idom/discussions
    about: Chat directly with fellow IDOM developers and users
